INSERT INTO dynamodb_fix_analysis(id,id_repository,sequencer,run_name,id_requestor,created_at,updated_at,time_requested,fix_type,new_repository,cram,new_cram,vcf,new_vcf,cram_size,new_cram_size,vcf_size,new_vcf_size)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
ON DUPLICATE KEY UPDATE 
id = VALUES(id)
, id_repository = VALUES(id_repository)
, sequencer = VALUES(sequencer)
, run_name = VALUES(run_name)
, id_requestor = VALUES(id_requestor)
, created_at = VALUES(created_at)
, updated_at = VALUES(updated_at)
, time_requested = VALUES(time_requested)
, fix_type = VALUES(fix_type)
, new_repository = VALUES(new_repository)
, cram = VALUES(cram)
, new_cram = VALUES(new_cram)
, vcf = VALUES(vcf)
, new_vcf = VALUES(new_vcf)
, cram_size = VALUES(cram_size)
, new_cram_size = VALUES(new_cram_size)
, vcf_size = VALUES(vcf_size)
, new_vcf_size = VALUES(new_vcf_size)