INSERT INTO dynamodb_fix_samples(id,id_repository,id_library,sequencer,id_requestor,created_at,updated_at,time_requested,fix_type,new_repository,new_library,id_zlims_index,new_index)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
ON DUPLICATE KEY UPDATE 
id = VALUES(id)
, id_repository = VALUES(id_repository)
, id_library = VALUES(id_library)
, sequencer = VALUES(sequencer)
, id_requestor = VALUES(id_requestor)
, created_at = VALUES(created_at)
, updated_at = VALUES(updated_at)
, time_requested = VALUES(time_requested)
, fix_type = VALUES(fix_type)
, new_repository = VALUES(new_repository)
, new_library = VALUES(new_library)
, id_zlims_index = VALUES(id_zlims_index)
, new_index = VALUES(new_index)