INSERT INTO phenovar_institutions(
    id,
    name,
    satu_sehat_code,
    facility_code,
    facility,
    province_code,
    province,
    district_code,
    district,
    subdistrict_code,
    subdistrict,
    village_code,
    village,
    `status`,
    source,
    created_by,
    updated_by,
    created_at,
    updated_at
)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
ON DUPLICATE KEY UPDATE 
    `name` = VALUES(`name`),
    satu_sehat_code = VALUES(satu_sehat_code),
    facility_code = VALUES(facility_code),
    facility = VALUES(facility),
    province_code = VALUES(province_code),
    province = VALUES(province),
    district_code = VALUES(district_code),
    district = VALUES(district),
    subdistrict_code = VALUES(subdistrict_code),
    subdistrict = VALUES(subdistrict),
    village_code = VALUES(village_code),
    village = VALUES(village),
    `status` = VALUES(`status`),
    source = VALUES(source),
    created_by = VALUES(created_by),
    updated_by = VALUES(updated_by),
    updated_at = VALUES(updated_at);
