INSERT INTO ztronpro_analysis(
    data_creation_date,
    id_repository,
    run_folder_name,
    predicted_sex,
    percent_dups,
    percent_gc,
    percent_mapped,
    percent_proper_pairs,
    at_least_30x,
    at_least_20x,
    at_least_10x,
    depth,
    vars,
    snp,
    indel,
    ts_tv,
    Read_raw,
    Read_clean,
    Rate_clean,
    created_at,
    updated_at
)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
ON DUPLICATE KEY UPDATE 
    data_creation_date = VALUES(data_creation_date),
    id_repository = VALUES(id_repository),
    run_folder_name = VALUES(run_folder_name),
    predicted_sex = VALUES(predicted_sex),
    percent_dups = VALUES(percent_dups),
    percent_gc = VALUES(percent_gc),
    percent_mapped = VALUES(percent_mapped),
    percent_proper_pairs = VALUES(percent_proper_pairs),
    at_least_30x = VALUES(at_least_30x),
    at_least_20x = VALUES(at_least_20x),
    at_least_10x = VALUES(at_least_10x),
    depth = VALUES(depth),
    vars = VALUES(vars),
    snp = VALUES(snp),
    indel = VALUES(indel),
    ts_tv = VALUES(ts_tv),
    Read_raw = VALUES(Read_raw),
    Read_clean = VALUES(Read_clean),
    Rate_clean = VALUES(Rate_clean),
    updated_at = VALUES(updated_at)
