INSERT INTO ztronpro_samples(starting_sample,original_sample_id,original_sample_name,if_urgent, product_name,`order`,project_code,project_name,sample_progress,total_routes,workflow,start_plate_code,start_well,id_library,barcode,dnb_id,flow_cell_id,start_time,completion_time,batch_number,contract_number,`zone`,creator,creation_time,last_modified_by,last_modified_time,created_at,updated_at)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
ON DUPLICATE KEY UPDATE starting_sample = VALUES(starting_sample),
original_sample_name = VALUES(original_sample_name),
if_urgent = VALUES(if_urgent), 
product_name = VALUES(product_name),
`order` = VALUES(`order`),
project_code = VALUES(project_code),
project_name = VALUES(project_name),
sample_progress = VALUES(sample_progress),
total_routes = VALUES(total_routes),
workflow = VALUES(workflow),
start_plate_code = VALUES(start_plate_code),
start_well = VALUES(start_well),
id_library = VALUES(id_library),
barcode = VALUES(barcode),
dnb_id = VALUES(dnb_id),
flow_cell_id = VALUES(flow_cell_id),
start_time = VALUES(start_time),
completion_time = VALUES(completion_time),
batch_number = VALUES(batch_number),
contract_number = VALUES(contract_number),
`zone` = VALUES(`zone`),
creator = VALUES(creator),
creation_time = VALUES(creation_time),
last_modified_by = VALUES(last_modified_by),
last_modified_time = VALUES(last_modified_time),
updated_at = VALUES(updated_at)